# Generated by Django 4.2.4 on 2023-10-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=50)),
                ('birthday', models.DateField(help_text='jj/mm/aaaa', verbose_name='Date de naissance')),
                ('gender', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'persons',
            },
        ),
    ]
