# Generated by Django 4.2.4 on 2023-10-06 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_person', '0004_alter_person_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='phone',
            field=models.CharField(default='default', max_length=20),
            preserve_default=False,
        ),
    ]
