# Generated by Django 4.2.4 on 2023-10-04 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_vehicle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='company',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='guaranttee',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='type_contract',
        ),
    ]
