# Generated by Django 4.2.4 on 2023-10-04 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_contract', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='agent',
            field=models.CharField(max_length=300),
        ),
    ]
