# Generated by Django 4.2.4 on 2023-10-03 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=150)),
                ('comment', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'db_table': 'others',
            },
        ),
    ]
