# Generated by Django 4.2.4 on 2023-10-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_dommage', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='description',
            field=models.CharField(max_length=1500),
        ),
    ]
